# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'ko-KR'
early_access: false
reviews:
  profile: 'chill' # chill | assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ['.*']
chat:
  auto_reply: true
